// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAW3XRbW9o177bMDcuprQ-a5DV8pwJw1tM',
    appId: '1:380708037345:web:1f296c04574466df5e4da0',
    messagingSenderId: '380708037345',
    projectId: 'meal-ver2',
    authDomain: 'meal-ver2.firebaseapp.com',
    storageBucket: 'meal-ver2.appspot.com',
    measurementId: 'G-Y1H3L33J92',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCundSBn3Wnx2zvXOfF-Wg0hOOlifrXSPY',
    appId: '1:380708037345:android:3bcddeeb23b9364b5e4da0',
    messagingSenderId: '380708037345',
    projectId: 'meal-ver2',
    storageBucket: 'meal-ver2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhbWmBsNkcq0jOov8no3C4BP2R3NCx1Y8',
    appId: '1:380708037345:ios:43b3a8d5525df2355e4da0',
    messagingSenderId: '380708037345',
    projectId: 'meal-ver2',
    storageBucket: 'meal-ver2.appspot.com',
    iosBundleId: 'com.example.mealVer2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhbWmBsNkcq0jOov8no3C4BP2R3NCx1Y8',
    appId: '1:380708037345:ios:43b3a8d5525df2355e4da0',
    messagingSenderId: '380708037345',
    projectId: 'meal-ver2',
    storageBucket: 'meal-ver2.appspot.com',
    iosBundleId: 'com.example.mealVer2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAW3XRbW9o177bMDcuprQ-a5DV8pwJw1tM',
    appId: '1:380708037345:web:6aa8b58a0f667e255e4da0',
    messagingSenderId: '380708037345',
    projectId: 'meal-ver2',
    authDomain: 'meal-ver2.firebaseapp.com',
    storageBucket: 'meal-ver2.appspot.com',
    measurementId: 'G-17E7BQTSB4',
  );

}