// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBF0K6qn0gsWZ2FmA377Ryl_PwiRTUCY5E',
    appId: '1:839505388310:web:30a81860f92a6bf348e637',
    messagingSenderId: '839505388310',
    projectId: 'meal-v2',
    authDomain: 'meal-v2.firebaseapp.com',
    storageBucket: 'meal-v2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeBPj_7Ojth3aJSl0mZyVaUxjs_WnZf6Y',
    appId: '1:839505388310:android:782773d5ee464c2448e637',
    messagingSenderId: '839505388310',
    projectId: 'meal-v2',
    storageBucket: 'meal-v2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxmQWHFYiD8XW32Jc5VYmYwrIIaDA6LDI',
    appId: '1:839505388310:ios:6008985155f36c8448e637',
    messagingSenderId: '839505388310',
    projectId: 'meal-v2',
    storageBucket: 'meal-v2.appspot.com',
    iosBundleId: 'com.example.mealVer2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxmQWHFYiD8XW32Jc5VYmYwrIIaDA6LDI',
    appId: '1:839505388310:ios:6008985155f36c8448e637',
    messagingSenderId: '839505388310',
    projectId: 'meal-v2',
    storageBucket: 'meal-v2.appspot.com',
    iosBundleId: 'com.example.mealVer2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBF0K6qn0gsWZ2FmA377Ryl_PwiRTUCY5E',
    appId: '1:839505388310:web:c0a820489d4b929348e637',
    messagingSenderId: '839505388310',
    projectId: 'meal-v2',
    authDomain: 'meal-v2.firebaseapp.com',
    storageBucket: 'meal-v2.appspot.com',
  );
}
